In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
a + 1

array([2, 3, 4, 5])

In [5]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [6]:
b = np.ones(4) + 1

In [7]:
a - b

array([-1.,  0.,  1.,  2.])

In [8]:
a * b

array([2., 4., 6., 8.])

In [9]:
j = np.arange(5)

In [10]:
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [11]:
a = np.arange(10000)

In [12]:
%timeit a + 1 

34 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [13]:
l = range(10000)

In [14]:
%timeit [i+1 for i in l] 

5.47 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
c = np.ones((3, 3))

In [16]:
c * c  

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [18]:
a = np.array([1, 2, 3, 4])

In [19]:
b = np.array([4, 2, 2, 4])

In [20]:
a == b

array([False,  True, False,  True])

In [21]:
a > b

array([False, False,  True, False])

In [22]:
a = np.array([1, 1, 0, 0], dtype=bool)

In [23]:
b = np.array([1, 0, 1, 0], dtype=bool)

In [24]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [25]:
np.logical_and(a, b)

array([ True, False, False, False])

In [26]:
a = np.arange(5)

In [27]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [28]:
np.log(a)

C:\Users\Acer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [29]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [30]:
a = np.arange(4)

In [31]:
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [32]:
a = np.triu(np.ones((3, 3)), 1)

In [33]:
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [34]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [35]:
a += a.T

In [36]:
x = np.array([1, 2, 3, 4])

In [37]:
np.sum(x)

10

In [38]:
x.sum()

10

In [39]:
x = np.array([[1, 1], [2, 2]])

In [40]:
x

array([[1, 1],
       [2, 2]])

In [41]:
x.sum(axis=0)

array([3, 3])

In [42]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [43]:
x.sum(axis=1)

array([2, 4])

In [44]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

In [45]:
x = np.random.rand(2, 2, 2)

In [46]:
x.sum(axis=2)[0,1]

1.2676844930149325

In [47]:
x[0, 1, :].sum()

1.2676844930149325

In [48]:
x = np.array([1, 3, 2])

In [49]:
x.min()

1

In [50]:
x.max()

3

In [51]:
x.argmin()

0

In [52]:
x.argmax()

1

In [53]:
np.all

<function numpy.all(a, axis=None, out=None, keepdims=<no value>)>

In [54]:
np.any

<function numpy.any(a, axis=None, out=None, keepdims=<no value>)>

In [55]:
a = np.zeros((100, 100))

In [56]:
np.any(a != 0)

False

In [57]:
np.all(a == a)

True

In [58]:
a = np.array([1, 2, 3, 2])

In [59]:
b = np.array([2, 2, 3, 2])

In [60]:
c = np.array([6, 4, 4, 5])

In [61]:
((a <= b) & (b <= c)).all()

True

In [62]:
x = np.array([1, 2, 3, 1])

In [63]:
y = np.array([[1, 2, 3], [5, 6, 1]])

In [64]:
x.mean()

1.75

In [65]:
np.median(x)

1.5

In [66]:
np.median(y, axis=-1)

array([2., 5.])

In [67]:
x.std() 

0.82915619758885

In [69]:
!cat data/populations.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [70]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T

In [71]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [72]:
b = np.array([0, 1, 2])

In [73]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [74]:
a = np.ones((4, 5))

In [75]:
a[0] = 2 

In [76]:
a

array([[2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
a = np.arange(0, 40, 10)

In [78]:
a.shape

(4,)

In [79]:
a = a[:, np.newaxis]

In [80]:
a.shape

(4, 1)

In [81]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [82]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [83]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]

In [84]:
distance = np.sqrt(x ** 2 + y ** 2)

In [85]:
distance

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

In [88]:
x, y = np.ogrid[0:5, 0:5]

In [89]:
x, y

(array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]]))

In [90]:
x.shape, y.shape

((5, 1), (1, 5))

In [91]:
distance = np.sqrt(x ** 2 + y ** 2)

In [92]:
x, y = np.mgrid[0:4, 0:4]

In [93]:
x

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [94]:
y

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [95]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [96]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [97]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [100]:
a.shape

(2, 3)

In [101]:
b = a.ravel()

In [102]:
b = b.reshape((2,3))

In [103]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
a.reshape((2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
b[0, 0] = 99

In [106]:
a

array([[99,  2,  3],
       [ 4,  5,  6]])

In [107]:
a = np.zeros((3, 2))

In [108]:
b = a.T.reshape(3*2)

In [110]:
b[0] = 9

In [111]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [112]:
z = np.array([1, 2, 3])

In [113]:
z

array([1, 2, 3])

In [114]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [115]:
z[np.newaxis, :]

array([[1, 2, 3]])

In [116]:
a = np.arange(4*3*2).reshape(4, 3, 2)

In [117]:
a.shape

(4, 3, 2)

In [118]:
a[0, 2, 1]

5

In [119]:
b = a.transpose(1, 2, 0)

In [120]:
b.shape

(3, 2, 4)

In [121]:
b[2, 1, 0]

5

In [122]:
b[2, 1, 0] = -1

In [123]:
a[0, 2, 1]

-1

In [124]:
a = np.arange(4)

In [125]:
a.resize((8,))

In [126]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [127]:
b = a

In [128]:
a.resize((4,)) 

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [129]:
a = np.array([[4, 3, 5], [1, 2, 1]])

In [130]:
b = np.sort(a, axis=1)

In [131]:
b

array([[3, 4, 5],
       [1, 1, 2]])

In [132]:
a.sort(axis=1)

In [133]:
a

array([[3, 4, 5],
       [1, 1, 2]])

In [134]:
a = np.array([4, 3, 1, 2])

In [135]:
j = np.argsort(a)

In [136]:
j

array([2, 3, 1, 0], dtype=int64)

In [137]:
a[j]

array([1, 2, 3, 4])

In [138]:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)