In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])

In [2]:
a

array([0, 1, 2, 3])

In [3]:
L = range(1000)

%timeit [i**2 for i in L]

415 µs ± 18.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a = np.arange(1000)

%timeit a**2

2.21 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
np.array?

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.  This argument can only be used to 'upcast' the array.  For
    downcasting, use the .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [7]:
np.lookfor('create array')

TypeError: 'NoneType' object is not iterable

In [9]:
np.arr*?

np.array
np.array2string
np.array_equal
np.array_equiv
np.array_repr
np.array_split
np.array_str

# <font color='blue'> Membuat Array Dengan Numpy </color>

### Manual construction of arrays

In [17]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [16]:
a.ndim

1

In [13]:
a.shape

(4,)

In [14]:
len(a)

4

In [15]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
b.shape

(2, 3)

In [19]:
len(b)

2

In [20]:
c = np.array([[[1], [2]], [[3], [4]]])

In [21]:
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [22]:
c.shape

(2, 2, 1)

In [23]:
c.ndim

3

In [24]:
len(c)

2

### Functions for creating arrays

In [35]:
a = np.arange(8) # 0 .. n-1  (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
a1 = np.arange(1,8)
a1

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

array([1, 3, 5, 7])

In [38]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [39]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

In [40]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [43]:
c = np.eye(9)
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [50]:
a = np.random.rand(4)       # uniform in [0, 1]
a

array([0.6979398 , 0.2582965 , 0.91580782, 0.53235819])

In [52]:
a2 = np.random.rand(4,4)       # uniform in [0, 1]
a2

array([[0.97881821, 0.2032152 , 0.66702606, 0.57478427],
       [0.05197529, 0.5428381 , 0.20794911, 0.09109018],
       [0.86985571, 0.02736978, 0.96862452, 0.32749989],
       [0.41027796, 0.13554422, 0.12706631, 0.41398398]])

In [68]:
b = np.random.randn(4)      # Gaussian
b

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851])

In [69]:
np.random.seed(1234)        # Setting the random seed

In [70]:
np.empty(1)

array([0.69359851])

# Basic data types

In [71]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [72]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

In [73]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

In [74]:
a = np.ones((3, 3))
a.dtype

dtype('float64')